# Generated by Django 4.1.1 on 2022-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
