# Generated by Django 4.1.1 on 2022-09-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_thing_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='until',
        ),
    ]
